name: Copy
on: 
  push:
    branches: [ master ]

jobs:
  copy:
    runs-on: ubuntu-latest
    env:
      my_secret: ${{secrets.PERSONAL_TOKEN}}
    steps:
    - uses: actions/checkout@v1
    - uses: subosito/flutter-action@v1
      with:
        channel: beta
    - run: |
        flutter config --enable-web
        flutter pub get
        flutter build web
        cp -R build/web/ public-flutter/
    - uses: andstor/copycat-action@v3
      with:
        personal_token: ${{ secrets.PERSONAL_TOKEN }}
        src_path: public-flutter/
        dst_path: /
        dst_owner: himanshusharma89
        dst_repo_name: 100DaysOfFlutter
        dst_branch: master
        src_branch: master
        username: himanshusharma89
        email: ranubhardwaj89@gmail.com
